[2025-01-16T13:21:24.221+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_processing_dag.spark_submit_job manual__2025-01-16T13:21:22.432144+00:00 [queued]>
[2025-01-16T13:21:24.226+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_processing_dag.spark_submit_job manual__2025-01-16T13:21:22.432144+00:00 [queued]>
[2025-01-16T13:21:24.226+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-01-16T13:21:24.232+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): spark_submit_job> on 2025-01-16 13:21:22.432144+00:00
[2025-01-16T13:21:24.238+0000] {standard_task_runner.py:57} INFO - Started process 127 to run task
[2025-01-16T13:21:24.238+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_processing_dag', 'spark_submit_job', 'manual__2025-01-16T13:21:22.432144+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/spark-processing.py', '--cfg-path', '/tmp/tmpg4ipu9uy']
[2025-01-16T13:21:24.240+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask spark_submit_job
[2025-01-16T13:21:24.275+0000] {task_command.py:416} INFO - Running <TaskInstance: spark_processing_dag.spark_submit_job manual__2025-01-16T13:21:22.432144+00:00 [running]> on host 3c782527ad0c
[2025-01-16T13:21:24.330+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_processing_dag' AIRFLOW_CTX_TASK_ID='spark_submit_job' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T13:21:22.432144+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-16T13:21:22.432144+00:00'
[2025-01-16T13:21:24.338+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2025-01-16T13:21:24.339+0000] {spark_submit.py:340} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark --verbose /opt/spark-apps/sample_spark_app.py /opt/spark-data/input /opt/spark-data/output
[2025-01-16T13:21:24.440+0000] {spark_submit.py:491} INFO - /home/***/.local/lib/python3.8/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-01-16T13:21:24.440+0000] {spark_submit.py:491} INFO - JAVA_HOME is not set
[2025-01-16T13:21:24.448+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark --verbose /opt/spark-apps/sample_spark_app.py /opt/spark-data/input /opt/spark-data/output. Error code is: 1.
[2025-01-16T13:21:24.451+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_processing_dag, task_id=spark_submit_job, execution_date=20250116T132122, start_date=20250116T132124, end_date=20250116T132124
[2025-01-16T13:21:24.459+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 15 for task spark_submit_job (Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark --verbose /opt/spark-apps/sample_spark_app.py /opt/spark-data/input /opt/spark-data/output. Error code is: 1.; 127)
[2025-01-16T13:21:24.471+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-16T13:21:24.483+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
